services:
    web:
        depends_on:
            - mongodb
        container_name: vut-tasker-webserver
        build:
            dockerfile: ./server/Dockerfile
            context: ./
        ports:
            - 80:80
            - 3000:3000
        environment:
            - NGINX_PORT=80
        volumes:
            - ./server/src:/usr/src/app/src
            - ./shared:/usr/src/shared
            - ./.env:/usr/src/app/.env
        restart: unless-stopped
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - ${DATABASE_PORT}:27017
        volumes:
            - ./mongodb:/data/db:rw
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
