services:
    web:
        container_name: vut-tasker-web
        image: nginx:latest
        volumes:
            - ./web/dist:/usr/share/nginx/html
        environment:
            - NGINX_PORT=80
        ports:
            - 80:80
        restart: unless-stopped
    api:
        container_name: vut-tasker-api
        build:
            context: ./server/
        ports:
            - 3000:3000
        restart: unless-stopped
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        ports:
            - ${DATABASE_PORT}:27017
        volumes:
            - ./mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
