services:
  web:
    container_name: vut-tasker-web
    image: nginx:latest
    volumes:
      - ./web/dist:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=80
    ports:
      - 80:80
    restart: unless-stopped
  api:
    tty: true
    depends_on:
      - mongodb
    container_name: vut-tasker-api
    build:
      dockerfile: ./server/Dockerfile
      context: ./
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/usr/src/app/src
      - ./shared:/usr/src/shared
      - ./.env:/usr/src/.env
    restart: unless-stopped
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
