import type { User } from "../Entities/User.ts";

export const USERS: User[] = [
  {
    nick: "DamDam",
    subscribed_subjects: [],
    color: "#f96004",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "Agar",
    subscribed_subjects: [],
    color: "skyblue",
    show_my_progress: false,
    show_me_progress: false,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "gtrhag",
    subscribed_subjects: [],
    color: "yellow",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "Adamek",
    subscribed_subjects: [],
    color: "purple",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "Momow",
    subscribed_subjects: [],
    color: "red",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "TeslaRam",
    subscribed_subjects: [],
    color: "#0B27E4",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "AďoDomi",
    subscribed_subjects: [],
    color: "white",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
  {
    nick: "Džimo",
    subscribed_subjects: [],
    color: "#FF69B4",
    show_my_progress: true,
    show_me_progress: true,
    forename: "",
    surname: "",
    xlogin: null,
  },
];
