import type { User } from "../Entities/User.ts";

export const USERS: User[] = [
  {
    nick: "DamDam",
    fullname: "Damián",
    subscribed_subjects: [],
    color: "#f96004",
    show_my_progress: true,
    show_me_progress: true,
  },
  {
    nick: "Agar",
    fullname: "Kristián",
    subscribed_subjects: [],
    color: "skyblue",
    show_my_progress: false,
    show_me_progress: false,
  },
  {
    nick: "gtrhag",
    fullname: "Sebastián",
    subscribed_subjects: [],
    color: "yellow",
    show_my_progress: true,
    show_me_progress: true,
  },
  {
    nick: "Adamek",
    fullname: "Adam",
    subscribed_subjects: [],
    color: "purple",
    show_my_progress: true,
    show_me_progress: true,
  },
  {
    nick: "Momow",
    fullname: "Šimon",
    subscribed_subjects: [],
    color: "red",
    show_my_progress: true,
    show_me_progress: true,
  },
  {
    nick: "TeslaRam",
    fullname: "Roman",
    subscribed_subjects: [],
    color: "#0B27E4",
    show_my_progress: true,
    show_me_progress: true,
  },
  {
    nick: "AďoDomi",
    fullname: "Andrej",
    subscribed_subjects: [],
    color: "white",
    show_my_progress: true,
    show_me_progress: true,
  },
  {
    nick: "Džimo",
    fullname: "Andrej",
    subscribed_subjects: [],
    color: "#FF69B4",
    show_my_progress: true,
    show_me_progress: true,
  },
];
